version: '3.6'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${VERSION-6.4.0}
    environment:
      # - discovery.type=single-node
      - bootstrap.memory_lock=true
      - indices.fielddata.cache.size=20%
      - network.publish_host=${ES_PUBLISH}
      - "ES_JAVA_OPTS=-Xms${ES_HEAP} -Xmx${ES_HEAP} -Des.scripting.exception_for_missing_value=true"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      nofile: 65536
      memlock: -1
    ports:
      - '9200:9200'
      - 9300
    restart: always
    deploy:
      resources:
        limits:
          memory: ${ES_MEM}
  es_hq:
    image: elastichq/elasticsearch-hq
    environment:
      - HQ_DEFAULT_URL=http://${ES_PUBLISH}:9200
    ports:
      - '9400:5000'
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:${VERSION-6.4.0}
    environment:
      - NODE_OPTIONS=--max-old-space-size=200
    labels:
      parse.flow: json.kibana
    ports:
      - '5601:5601'
    restart: always
    deploy:
      resources:
        limits:
          memory: 200m
  fluentd:
    image: ermaker/fluentd
    environment:
      - LOGSPOUT=ignore
      - RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR=0.9
    ulimits:
      nofile: 65536
    ports:
      - '5160:5160/udp'
      - '5170:5170'
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.40'
          # memory: 16m
          memory: 256m
    volumes: # TODO
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf:ro
      - buffer:/fluentd/log
volumes:
  elasticsearch:
  buffer:
