# Module: kibana
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/6.4/metricbeat-module-kibana.html

- module: kibana
  metricsets:
    - status
  period: 10s
  hosts: '${KIBANA_HOST}'
  enabled: '${METRIC_KIBANA}'
  #basepath: ""
  #username: "user"
  #password: "secret"
