version: '2.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION-7.1.1}
    environment:
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=$ES_PASSWORD
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - indices.fielddata.cache.size=20%
      - network.publish_host=${ES_PUBLISH}
      - "ES_JAVA_OPTS=-Xms${ES_HEAP} -Xmx${ES_HEAP} -Des.scripting.exception_for_missing_value=true"
    labels:
      parse.flow: json.elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      nofile: 65536
      memlock: -1
    ports:
      - '9200:9200'
      - 9300
    restart: always
    mem_limit: ${ES_MEM}
  es_hq:
    image: elastichq/elasticsearch-hq
    environment:
      - HQ_DEFAULT_URL=http://${ES_USERNAME}:${ES_PASSWORD}@${ES_PUBLISH}:9200
    ports:
      - '9400:5000'
  kibana:
    image: docker.elastic.co/kibana/kibana:${VERSION-7.1.1}
    environment:
      - ELASTICSEARCH_USERNAME=$ES_USERNAME
      - ELASTICSEARCH_PASSWORD=$ES_PASSWORD
      - NODE_OPTIONS=--max-old-space-size=200
    labels:
      parse.flow: json.kibana
    ports:
      - '5601:5601'
    restart: always
    mem_limit: 200m
  fluentd:
    image: ermaker/fluentd
    environment:
      - ES_USERNAME
      - ES_PASSWORD
      - no_proxy=elasticsearch,${no_proxy}
      - LOGSPOUT=ignore
      - RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR=0.9
    ulimits:
      nofile: 65536
    ports:
      - '5160:5160/udp'
      - '5170:5170'
      - '24224:24224'
      - '24224:24224/udp'
      - '9880:9880'
    restart: always
    cpus: 0.4
    mem_limit: 256m
    volumes: # TODO
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf:ro
      - buffer:/fluentd/log
volumes:
  elasticsearch:
  buffer:
