# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/6.4/metricbeat-module-elasticsearch.html

- module: elasticsearch
  metricsets:
    - node
    - node_stats
  period: 10s
  hosts: '${ES_HOSTS}'
  enabled: '${METRIC_ES}'
  #username: "user"
  #password: "secret"
