version: '2.3'
services:
  logspout:
    image: gliderlabs/logspout
    command: ${FLUENTD_HOST-raw://localhost:5160}
    environment:
      - 'RAW_FORMAT={"@timestamp":{{ toJSON .Time }},"message":{{ toJSON .Data }},"tag":{{ toJSON ( index .Container.Config.Labels "parse.flow" ) }},"docker":{"hostname":{{ toJSON .Container.Config.Hostname }},"name":{{ toJSON .Container.Name }},"project":{{ toJSON ( index .Container.Config.Labels "com.docker.compose.project" ) }},"service":{{ toJSON ( or ( index .Container.Config.Labels "com.docker.compose.service" ) .Container.Name ) }},"number":{{ toJSON ( index .Container.Config.Labels "com.docker.compose.container-number" ) }},"id":{{ toJSON .Container.ID }}}}'
      - TAIL=500
      - PORT=4226
    volumes:
      # - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: host
    restart: always
    mem_limit: 16m
    cpus: 0.2
  metricbeat:
    image: docker.elastic.co/beats/metricbeat-oss:${VERSION-6.4.0}
    command: -e --system.hostfs=/hostfs --strict.perms=false
    user: root
    environment:
      - ES_HOSTS=${ES_HOSTS-http://localhost:9200}
      - BEAT_DASHBOARDS=${BEAT_DASHBOARDS-false}
      - KIBANA_HOST=${KIBANA_HOST-http://localhost:5601}
      - METRIC_KIBANA=${METRIC_KIBANA-false}
      - METRIC_ES=${METRIC_ES-false}
    volumes:
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /etc/hostname:/etc/hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - ./metricbeat/modules.d:/usr/share/metricbeat/modules.d:ro
    network_mode: host
    restart: always
    mem_limit: 64m
    cpus: 0.2
